### ISSUE TITLE
Problem with creating files

### ISSUE THREAD

**Issue by mstaniszczak** [collective/plone.jsonapi.routes#77] opened 2016-02-23 14:29 UTC
When I try to create new file via http://127.0.0.1:8080/Plone/@@API/plone/api/1.0/files/create
I get exception like this:

```
_process_input() got multiple values for keyword argument 'file'", "success": false, "error": "Traceback (most recent call last):
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/plone.jsonapi.core-0.5-py2.7.egg/plone/jsonapi/core/browser/decorators.py\", line 18, in decorator
    return f(*args, **kwargs)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/plone.jsonapi.core-0.5-py2.7.egg/plone/jsonapi/core/browser/api.py\", line 59, in render
    return self.dispatch()
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/plone.jsonapi.core-0.5-py2.7.egg/plone/jsonapi/core/browser/api.py\", line 53, in dispatch
    return router(self.context, self.request, path)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/plone.jsonapi.core-0.5-py2.7.egg/plone/jsonapi/core/browser/router.py\", line 136, in __call__
    return self.view_functions[endpoint](context, request, **values)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/plone.jsonapi.routes-0.8.4-py2.7.egg/plone/jsonapi/routes/providers/files.py\", line 29, in create
    items = create_items(\"File\", request, uid=uid, endpoint=\"files\")
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/plone.jsonapi.routes-0.8.4-py2.7.egg/plone/jsonapi/routes/api.py\", line 136, in create_items
    update_object_with_data(obj, record)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/plone.jsonapi.routes-0.8.4-py2.7.egg/plone/jsonapi/routes/api.py\", line 1260, in update_object_with_data
    success = dm.set(k, v, **record)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/plone.jsonapi.routes-0.8.4-py2.7.egg/plone/jsonapi/routes/datamanagers.py\", line 155, in set
    self._set(field, value, **kw)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/plone.jsonapi.routes-0.8.4-py2.7.egg/plone/jsonapi/routes/datamanagers.py\", line 166, in _set
    return mapply(mutator, value, **kw)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/Products.Archetypes-1.9.8-py2.7.egg/Products/Archetypes/utils.py\", line 130, in mapply
    return method(*call_args, **kw)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/Products.Archetypes-1.9.8-py2.7.egg/Products/Archetypes/ClassGen.py\", line 76, in generatedMutator
    return schema[name].set(self, value, **kw)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/wicked-1.1.12-py2.7.egg/wicked/fieldevent/__init__.py\", line 34, in store
    notify(store)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py\", line 31, in notify
    subscriber(event)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py\", line 24, in dispatch
    zope.component.subscribers(event, None)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py\", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py\", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py\", line 585, in subscribers
    subscription(*objects)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/wicked-1.1.12-py2.7.egg/wicked/fieldevent/__init__.py\", line 24, in notifyFieldEvent
    for ignore in subscribers((field, event), IFieldValueSetter):
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py\", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py\", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py\", line 589, in subscribers
    subscriber = subscription(*objects)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/wicked-1.1.12-py2.7.egg/wicked/fieldevent/meta.py\", line 83, in field_value_set
    _set(field, event.instance, event.value, **event.kwargs)
  File \"/home/mstaniszczak/projects/vnc/VCP-1.10.7/eggs/Products.Archetypes-1.9.8-py2.7.egg/Products/Archetypes/Field.py\", line 1142, in set
    **kwargs)
    TypeError: _process_input() got multiple values for keyword argument 'file'

```

JSON sent in request:
```
{
"creators": [
"admin"
],
"subject": [
"Test"
],
"description": "",
"language": "en",
"title": "Data-pdf.pdf",
"filename": "Data-pdf.pdf",
"file": "JVBERi0xLjQKJeLjz9MKNCAwIG9iago8PC9Db2xvclNwYWNlL0RldmljZUdyYXkvU3VidHlwZS9JbWFnZS9IZWlnaHQgMTYvRmlsdGVyL0ZsYXRlRGVjb2RlL1R5cGUvWE9iamVjdC9XaWR0aCAxNi9MZW5ndGggNDgvQml0c1BlckNvbXBvbmVudCA4Pj5zdHJlYW0KeJxjYEAB/xEsIEDj/kfnwgX+o/L/o/L/o/JJ4mKYDRdAcjQqFyyAy1voAABG6WuVCmVuZHN0cmVhbQplbmRvYmoKNSAwIG9iago8PC9Db2xvclNwYWNlL0RldmljZVJHQi9TdWJ0eXBlL0ltYWdlL0hlaWdodCAxNi9GaWx0ZXIvRmxhdGVEZWNvZGUvVHlwZS9YT2JqZWN0L1dpZHRoIDE2L1NNYXNrIDQgMCBSL0xlbmd0aCAxODUvQml0c1BlckNvbXBvbmVudCA4Pj5zdHJlYW0KeJz7/58EIKnliEfWMmkmHIEUazvjUWwa1TP38HcIci3bgd9kiGL/9st+rRf4xFUYGBiAWiQ07PEr9m0559N0WkrHVcM5EyiCVT1EcUDHVYhi74YTXrWHgQirepPIbohioDOQFXvVHcFUj+xmqOK6I7gUGwY3wRX7Np+FKgYjTMVaHgWz9n8EOsO/7SJBxRAgpesGlII4w7v+GMQluBQja4GaTEgxmhZiFCNrIVIxBJCkmCAAAIX8V/kKZW5kc3RyZWFtCmVuZG9iago3IDAgb2JqCjw8L0ZpbHRlci9GbGF0ZURlY29kZS9MZW5ndGggNzY0Pj5zdHJlYW0KeJztV99v0zAQfvdf4UdAk+f4Z7KngWAPSBOaqIQEQihtui2lbrbuBxJ/PXd20jhO2YCu0h5Yp9XffPf5uzuf41yTNxPCqS0EnVTk3YSckWvCGZdW0x9E0PcwuSAZp6fky1dOKyINtdpQR7QNo6UfScO4grEcDMP8JflEViSj+FlfEKlZ8TsSdPPT0bAjOQcp+AEKJagVgplAwTsALKZgQgPOWJEBVoLZCALJq4FzMj+CfpyZzpUzU+QQXPoNkoYrb2HuqYLimDeKwY1iGOGRe58XjYsaa5jOPZNBzxYjk2YINcslajIxCrkZEgwtEtSaasbzP8pPtPaIeci10R1zD4NxaTAjuIWCs0LCD02/UZ705toGeVrnXlHAyw3mguW+BsE8gZ017lXFCyzXo4wSzLBbOvsU95zYRNidmw6Mei1uwb6ngs9md2hLMUsy83J0B1CLQv3aKNb2IkrbwHaLRs7D+RGEsQyJeXRXDFbewtxTBcUxbxSDG8cwwql7kUP5+wKlCY8KogrArXkCdy/PgNeNlu0wNrzu101gZ72zjMDrRst2uNvxrXkCO+udZfwvynMqyuYEgbvC4Qk8xuGycA4PdPwvZoUJQ41SDOgmjrw4WTeOHr2cLPA+sYeCehUiUZFxCDP3MiB4lPG9vKqXt/Ob22P8wxZ3VXlzta5xXK+qumT3qxmb1j9boU+fmPapIMBZekUf76aL+ew2zc1T7rIHcwNKlPVKJpCFvcVtbdiGFs75sFqThvyUO/rBkHnOMuVFlJWrV8dY81njdoj9/wn1DE+oZ3jb2toa4aJr4cWGh135uXbTddlux60uEm4wsoh9/vJge+hsKuAtJT0Q9pPLrV2qMoGvMdGhfdqsDujJfEozfUAFh0kuj6CDX5/u0LLXuKxfUVBlcv+4wrNQ0Zmjh7W7yOjbhp4ltRuJzXnkiWJpnOGxuUzMP1RN861czy7r+3kVu8r0iQp3VqphOdmen5f1DYVfLDd1Zb1key3Vv6QYfc7IL1cYWToKZW5kc3RyZWFtCmVuZG9iagoxIDAgb2JqCjw8L0NvbnRlbnRzIDcgMCBSL1R5cGUvUGFnZS9SZXNvdXJjZXM8PC9Qcm9jU2V0IFsvUERGIC9UZXh0IC9JbWFnZUIgL0ltYWdlQyAvSW1hZ2VJXS9Gb250PDwvRjEgMiAwIFIvRjIgMyAwIFIvRjMgNiAwIFI+Pi9YT2JqZWN0PDwvaW1nMSA1IDAgUi9pbWcwIDQgMCBSPj4+Pi9QYXJlbnQgOCAwIFIvTWVkaWFCb3hbMCAwIDYxMiA3OTJdPj4KZW5kb2JqCjIgMCBvYmoKPDwvU3VidHlwZS9UeXBlMS9UeXBlL0ZvbnQvQmFzZUZvbnQvVGltZXMtQm9sZC9FbmNvZGluZy9XaW5BbnNpRW5jb2Rpbmc+PgplbmRvYmoKMyAwIG9iago8PC9TdWJ0eXBlL1R5cGUxL1R5cGUvRm9udC9CYXNlRm9udC9UaW1lcy1Sb21hbi9FbmNvZGluZy9XaW5BbnNpRW5jb2Rpbmc+PgplbmRvYmoKNiAwIG9iago8PC9TdWJ0eXBlL1R5cGUxL1R5cGUvRm9udC9CYXNlRm9udC9IZWx2ZXRpY2EvRW5jb2RpbmcvV2luQW5zaUVuY29kaW5nPj4KZW5kb2JqCjggMCBvYmoKPDwvS2lkc1sxIDAgUl0vVHlwZS9QYWdlcy9Db3VudCAxL0lUWFQoMi4xLjcpPj4KZW5kb2JqCjkgMCBvYmoKPDwvVHlwZS9DYXRhbG9nL1BhZ2VzIDggMCBSPj4KZW5kb2JqCjEwIDAgb2JqCjw8L01vZERhdGUoRDoyMDE2MDIyMjA1NDExNS0wOCcwMCcpL0NyZWF0aW9uRGF0ZShEOjIwMTYwMjIyMDU0MTE1LTA4JzAwJykvUHJvZHVjZXIoaVRleHQgMi4xLjcgYnkgMVQzWFQpPj4KZW5kb2JqCnhyZWYKMCAxMQowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDEzOTcgMDAwMDAgbiAKMDAwMDAwMTYwNiAwMDAwMCBuIAowMDAwMDAxNjk1IDAwMDAwIG4gCjAwMDAwMDAwMTUgMDAwMDAgbiAKMDAwMDAwMDIxNiAwMDAwMCBuIAowMDAwMDAxNzg1IDAwMDAwIG4gCjAwMDAwMDA1NjYgMDAwMDAgbiAKMDAwMDAwMTg3MyAwMDAwMCBuIAowMDAwMDAxOTM2IDAwMDAwIG4gCjAwMDAwMDE5ODEgMDAwMDAgbiAKdHJhaWxlcgo8PC9JbmZvIDEwIDAgUi9JRCBbPDFiOTZhZWQ4OTVjZDk5MDMzNmE2NTc2MWE1Mzk2MTU3PjwzYjg1YTRiODY5ZWI5ZjA3OTg0Zjc5ZmY1ZmVlZWQyZD5dL1Jvb3QgOSAwIFIvU2l6ZSAxMT4+CnN0YXJ0eHJlZgoyMTA0CiUlRU9GCg==",
"allowDiscussion": false,
"rights": "",
"excludeFromNav": false,
"parent_path": "/Plone/test-5",
"contributors": [
],
"effectiveDate": "",
"expirationDate": ""
}
```

**Comment by ramonski** [comment] 2016-02-23 14:57
Hi Marcin
Thanks for the report.
Could you please add the version info of `Plone`, `plone.jsonapi.core` and `plone.jsonapi.routes` to your report?
Thanks

**Comment by mstaniszczak** [comment] 2016-02-23 15:00
Of course:
Plone 4.3.4.1 (4309)
CMF 2.2.8
Zope 2.13.22
plone.jsonapi.core 0.5
plone.jsonapi.routes 0.8.4

**Comment by mstaniszczak** [comment] 2016-02-23 15:54
Probably problem is with kwargs from FileField.set(...) (from Products.Archetypes.Field). In this method I see:

```
        value, mimetype, filename = self._process_input(value, file=file,
                                                        instance=instance,
                                                        **kwargs)

```

And problem is, that here argument 'file' is sned publicly, but occurs also in kwargs. SO in fact is sent twice.

**Comment by ramonski** [comment] 2016-02-23 16:10
Thanks for the hint, that will reduce the time to find the root cause of the problem. Please feel free to send a PR at any time, as I won't be able to fix this issue in short time.
Regards, Ramon

**Comment by mstaniszczak** [comment] 2016-02-23 22:50
https://github.com/collective/plone.jsonapi.routes/pull/78

probably it can be more elegant, but works fine:)

**Comment by ramonski** [comment] 2016-04-07 16:11
Funny, this only seems to happen when `description` is sent with the JSON body

**Comment by ramonski** [comment] 2016-04-07 16:43
fixed with https://github.com/collective/plone.jsonapi.routes/pull/78

**Closed by ramonski** 2016-04-07 16:43 UTC
Labels: bug
